/**
 * Created by xukj on 2018/7/30.
 *
 */

// 协议定义
const REQUEST_SUCCESS = 200;
const BAD_REQUEST_ERROR = 400;
const UNAUTHORIZED_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const NOT_FOUND_ERROR = 404;
const NOT_ACCEPTABLE_ERROR = 406;
const REQUEST_TIMEOUT_ERROR = 408;
const INTERNAL_SERVER_ERROR = 500;
const SERVER_UNAVAILABLE = 503;
// 自定义
const USER_CLOSE_ERROR = -4000;
const UNKNOWN_ERROR = -9999;

export default {
    REQUEST_SUCCESS,
    BAD_REQUEST_ERROR,
    UNAUTHORIZED_ERROR,
    FORBIDDEN_ERROR,
    NOT_FOUND_ERROR,
    NOT_ACCEPTABLE_ERROR,
    REQUEST_TIMEOUT_ERROR,
    INTERNAL_SERVER_ERROR,
    SERVER_UNAVAILABLE,

    USER_CLOSE_ERROR,
    UNKNOWN_ERROR,
};